steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}' 
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'
      - '--platform'
      - 'managed'
      - '--region'
      - '${_REGION}' 

substitutions:
  _REGION: "asia-southeast1"
  _SERVICE_NAME: "ninkatec-cv"

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'